---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - batch.slo.operator.com
  resources:
  - slos
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch.slo.operator.com
  resources:
  - slos/status
  verbs:
  - get
  - patch
  - update
